# Generated by Django 5.1.2 on 2024-10-17 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_oder',
            new_name='date_order',
        ),
        migrations.RenameField(
            model_name='ordertime',
            old_name='oder',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='shippingaddreess',
            name='oder',
        ),
        migrations.AddField(
            model_name='shippingaddreess',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.order'),
        ),
    ]
